# This workflow compiles mcMMO, runs tests, and produces a working jar artifact.
name: Compile, Test & Build mcMMO Jar

on:
  # Trigger when source or pom changes
  push:
    paths:
      - 'src/**'
      - 'pom.xml'
      - '.github/workflows/maven.yml'

  # Trigger for pull requests touching source or pom
  pull_request:
    paths:
      - 'src/**'
      - 'pom.xml'

  # Allow manual runs from GitHub UI
  workflow_dispatch:

jobs:
  build:
    name: Maven Build & Jar Artifact
    runs-on: ubuntu-latest
    steps:

      # 1. Check out repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Java 17 JDK (Adopt)
      - name: Java 17 setup
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-package: jdk
          java-version: '17'

      # 3. Cache Maven dependencies
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # 4. Build with Maven (skip test reports but still run tests)
      - name: Build via Maven
        run: mvn clean package -B --file pom.xml -DdisableXmlReport=true

      # 5. Upload final plugin jar (assuming Maven target dir)
      - name: Upload mcMMO plugin jar
        uses: actions/upload-artifact@v4
        with:
          name: mcMMO-plugin
          path: target/*.jar
